using FizzBuzz.SourceGenerator;
using Microsoft.CodeAnalysis;
using System.Reflection;

namespace FizzBuzz.SourceGenerator
{
    public static class Consts
    {
        public static readonly SymbolDisplayFormat GlobalAlias = SymbolDisplayFormat.FullyQualifiedFormat
           //.WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.ExpandNullable | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier)
           .WithMemberOptions(SymbolDisplayMemberOptions.IncludeContainingType);

        public static readonly AssemblyName AssemblyName = typeof(FizzBuzzGenerator).Assembly.GetName();
        public static readonly string GeneratedCodeAttr = $@"global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{AssemblyName.Name}"", ""{AssemblyName.Version}"")";

        public static readonly string OptionAttrCode = $$"""
                   // <auto-generated/>
                   #nullable enable

                   namespace FizzBuzzGenerator
                   {
                       [{{GeneratedCodeAttr}}]
                       [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                       public sealed class ModuloOptionAttribute : global::System.Attribute
                       {
                           public int Divider { get;}
                           public string Text { get;}

                           public ModuloOptionAttribute(int divider, string text)
                           {
                               Divider = divider;
                               Text = text;
                           }
                       }
                   }
                   """;
    }
}

